### ISSUE TITLE
xeCJK: 在 \underline{} 之后添加额外的空格

### ISSUE THREAD

**Issue by ghost** [CTeX-org/ctex-kit#212]
\documentclass{article}
    \usepackage{ifxetex}
    \ifxetex
      \usepackage{xeCJK}
    \else
      \usepackage{zhmCJK}
    \fi
    \setCJKmainfont{FZSSK.TTF}
    \begin{document}
    这是一个\underline{下划线}命令测试。
    \end{document}

[贴吧](http://tieba.baidu.com/p/3869218182)上看到的。
上述例子在用 XeLaTeX 编译的时候，调用 `xeCJK` 宏包，「线」和「命」之间会有额外的空格；在使用 pdfLaTeX 编译的时候，调用 `zhmCJK` 宏包，则没有这个问题。

虽然最好是用 `xeCJKfntef` 的 \CJKunderline，不过这多少是个问题？不知道有没有修复的必要……？

**Comment by qinglee** [comment]
`\underline` 是 TeX 原语，本来只能用在数学模式之中，LaTeX 对它进行了修改：

```TeX
\let\@@underline\underline
\def\underline#1{%
  \relax
  \ifmmode\@@underline{#1}%
  \else $\@@underline{\hbox{#1}}\m@th$\relax\fi}
```

额外的空格是 xeCJK 检测到 `\lastnodetype` 是数学节点才自动加上的。`url` 包的 `\url` 也有类似的问题。

但我们在这里做不了什么，就留作已知问题吧。

**Comment by LiamHuang0205** [comment]
这样啊。

那确实没什么办法去修复，只能留作已知问题了。

**Comment by aminophen** [comment]
I cannot understand Chinese but:

I'm a member of Japanese pLaTeX / upLaTeX team ([texjporg](https://github.com/texjporg)), and  currently working on adaption to the latest pTeX / upTeX engines. We had a similar problem in (u)pLaTeX:
~~~~ tex
% uplatex test.tex => dvipdfmx test.dvi
\documentclass{ujarticle}
\begin{document}
あいう\underline{漢字}アイウ\par
あいう漢字アイウ
\end{document}
~~~~
There were unusual spaces before/after \underline{ }, so we changed the macro in (u)pLaTeX since 2016/05/07u00:
~~~~ tex
\def\underline#1{%
  \relax
  \ifmmode\@@underline{#1}%
  \else \leavevmode\null$\@@underline{\hbox{#1}}\m@th$\null\relax\fi}
~~~~
This may help solve the problem also in XeLaTeX and so on.

**Comment by qinglee** [comment]
@aminophen Many thanks for your attention!

Indeedly, you modification can help on this issue. But there may also be an unwanted side effect. There will be no `\kanjiskip` or `\xkanjiskip` inserted between `\underline` text and the surrounding text. See
```TeX
% !TeX program  = upLaTeX

\documentclass{ujarticle}

\begin{document}

\kanjiskip=\bigskipamount

漢字\underline{漢字}漢字\par
漢字\underline{abc}漢字\par
漢字abc漢字\par

\end{document}
```
So we decided to do nothing and eave it as is. Actually, we can use `\CJKunderline` in xeCJK. It is a better alternative.

**Comment by aminophen** [comment]
>  There will be no \kanjiskip or \xkanjiskip inserted between \underline text and the surrounding text.

Yes I know of course... that is a problem.

Only for information: the reason why we introduced the new definition to pLaTeX is, "restoring old behavior of pLaTeX." Actually, the result from the original old version of pLaTeX (in 2006) + old version of pTeX (in 2006) is exactly the same as what we have now with latest e-pTeX + pLaTeX (2016/05/07), both of which are unwanted, sigh...

Thanks for your attention (and also, thanks for the adaption described in #245)!
