### ISSUE TITLE
Documentation: really DVIPDFMx bug?

### ISSUE THREAD

**Issue by aminophen** [CTeX-org/ctex-kit#267]
ctex.pdf says

> 华文黑体不能通过这种方式使用:
> `\special{pdf:mapline unihei@Unicode@ unicode \detokenize{华文黑体}.ttf}`
> DVIPDFMx 不能生成 PDF,报下述错误:
> ** WARNING ** UCS-4 TrueType cmap table...
> ** ERROR ** Unable to read OpenType/TrueType Unicode cmap table.
> 如果将 CMap 改为 UniGB-UTF16-H,错误信息是
> ** WARNING ** No usable TrueType cmap table found for font "华文黑体.ttf".
> ** WARNING ** CID character collection for this font is set to "Adobe-GB1"
> ** ERROR ** Cannot continue without this...
> 在 pdfTEX 下生成的 PDF 只有方框23。华文细黑和华文仿宋的情况类似。这确认为 DVIPDFMx 的bug24。

Is this really a bug of DVIPDFMx? First, I guess the font itself "华文黑体.ttf" (or "华文细黑", "华文仿宋") does not support cmap Adobe-GB1, so it is natural that "UniGB-UTF16-H" specification fails. Also, the fonts seem to be protected against being embedded into pdf.

Anyway, I want a clearer MWE about the "bug"

~~~~
     * This part contains a bug. It may choose SJIS encoding TrueType cmap
     * table for Adobe-GB1.
~~~~

It would be better that the bug statement is removed if this is not actually a bug.

**Comment by Liam0205** [comment]
@clerkma might be interested to check this.
<https://github.com/clerkma/ptex-ng/blob/master/texk/libdpx/cidtype2.c#L597>

**Comment by aminophen** [comment]
I'll be glad if Clerk Ma can investigate it!

1. Is the "bug" in cidtype2.c valid/problematic? <- this is an issue with dvipdfmx, so actually not related to CTeX
2. Is the failure of font setting with CTeX + MacOSX triggered by the dvipdfmx "bug", or is something else responsible for it?

What do you think about the second point?

**Comment by clerkma** [comment]
The file 'STHeiti Light.ttc' (华文黑体) under macOS contains serveral Apple's TrueType-flavoured cmap tables. Those tables cannot be processed correctly by DVIPDFMx.

**Comment by Liam0205** [comment]
According to @clerkma 's effort, I got this (not very sure, just a brief analysis).

In `cidtype2.c`, there is an array [`known_encodings`](http://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/cidtype2.c?revision=41537&view=markup#l166). This array is used for select correct CMap table for each font opened.

* look through the array;
* check if CMap table is correct, by [`tt_cmap_read `](http://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/cidtype2.c?revision=41537&view=markup#l602) (it's [definition](http://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/tt_cmap.c?view=markup#l448));
* if the check is passed, break the loop.

There are serval tables in `华文黑体.ttf`, see the screenshot from @clerkma:
![image](https://cloud.githubusercontent.com/assets/3348485/22654774/d0972a66-ecc8-11e6-9653-0584a90cb40d.png)
As you can see, the first table is of format 12. On the other hand, we could collect information from the error report from DVIPDFMx:
> ** WARNING ** UCS-4 TrueType cmap table...

that, the first table, with format 12, is selected ([`cmap->format`](http://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/tt_cmap.c?view=markup#l514)), and hence [`read_cmap12`](http://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/tt_cmap.c?view=markup#l397) is called. Later, in [`otf_load_Unicode_CMap `](http://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/tt_cmap.c?view=markup#l1882), after `tt_cmap_read` being called three times, the error `Unable to read OpenType/TrueType Unicode cmap table.` is raised.

For `UniGB-UTF16-H`, since we cannot match platform and encoding in [the loop](http://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/cidtype2.c?revision=41537&view=markup#l601), the default table (SJIS encoding TrueType CMap table) is set ([line 611](http://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/cidtype2.c?revision=41537&view=markup#l611)).
