### ISSUE TITLE
The 為 character is not rendered properly

### ISSUE THREAD

**Issue by marmistrz** [CTeX-org/ctex-kit#409]
For example 因為 renders as on the attached screenshot on Arch Linux, using xelatex.
![Screenshot from 2019-03-19 15-50-40](https://user-images.githubusercontent.com/2914938/54615689-d1474180-4a5e-11e9-94ee-c5e6ca141b92.png)

**Comment by stone-zeng** [comment]
The default CJK font used in `ctex` bundle is Fandol, which contains only a limited amount of Chinese characters. Especially, the traditional Chinese is almost unavailable.

You may use other high quality fonts, e.g. Source  Han Serif/Sans, or may use commercial fonts.

**Comment by marmistrz** [comment]
And how can I set the font to `Noto Serif CJK TC`
In `xeCJK` I'd do
```
\setCJKmainfont{Noto Serif CJK TC}
```

**Comment by stone-zeng** [comment]
It should work if Noto Serif CJK were installed on your os. `noto-fonts-cjk` is available as an Arch Linux package.

At present, `fontset` option cannot load Source Han/Noto CJK, due to the lack of kaiti and fangsong. You may just use the default settings (fandol), and your `setCJKmainfont` etc command will overwrite the default font settings.

**Comment by RuixiZhang42** [comment]
@marmistrz When you compile a `ctex`-document under XeLaTeX, the class will automatically call `xeCJK` to setup Chinese fonts. So you should be able to write something like:
```tex
% !TeX program = XeLaTeX
\documentclass[fontset=none]{ctexart}% Do not setup any fonts and use personalized setup
\setCJKmainfont{Noto Serif CJK TC}
\setCJKsansfont{Noto Sans CJK TC}
...
```

**Comment by marmistrz** [comment]
@RuixiZhang42 thanks. This made the trick for the characters. Unfortunately, the punctuation is rendered incorrectly, the vertical offset is wrong: 
![punctuation](https://user-images.githubusercontent.com/2914938/55882085-31379080-5ba4-11e9-951a-e55a9f681a53.png)

**Comment by stone-zeng** [comment]
That's because you use the Traditional Chinese (TC) version. Taiwan uses traditional Chinese as well as punctuation positions different from mainland China. Source Han/Noto CJK project has done a lot of work to take those differences into consideration. More detail can be found in its [official readme](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf).

Simply, you may just try

```latex
% !TeX program = XeLaTeX
\documentclass[fontset=none]{ctexart}% Do not set up any fonts and use personalized setup
\setCJKmainfont{Noto Serif CJK SC}
\setCJKsansfont{Noto Sans CJK SC}
...
```

then the punctuation will be "correct" (as in mainland China), but the characters may still keep in the traditional script.

**Comment by marmistrz** [comment]
So it's actually not a bug, but a feature. I haven't noticed it before, but it looks like this on Taiwanese websites indeed. 謝謝!
